### ISSUE TITLE
Further HugSQL integration

### ISSUE THREAD

**Issue by d-t-w** [troy-west/arche#2]
Do we want to support extending the HugsQL integration, we could support more dynamic use-cases (rather than just prepared statements).

**Comment by jsofra** [comment]
This could be achieved via implementing a HugsQL adaptor. Details on how to do that are included in the HugsQL documentation. [https://www.hugsql.org/#adapter-creation](https://www.hugsql.org/#adapter-creation)

**Comment by d-t-w** [comment]
close for now
